//Generated by ServiceNow SDK

declare const Class: any

declare namespace global {
declare class JSUtil{ static union(maps?) static removeFromMap(map?,names?) static isEmpty(item?) static has(item?) static doesNotHave(item?) static nil(item?) static notNil(item?) static getGlobal() static instance_of(item?,klass?) static _isString(val?) static type_of(value?) static typeOf(x?) static isJavaObject(value?) static toBoolean(item?) static getBooleanValue(gr?,field?) static contains(container?,value?,compareByIdentity?) static areEqual(val1?,val2?,logDiff?) static logObject(obj?,name?) static describeObject(obj?,name?) static _describeObject(obj?,name?,lead?,level?,result?) static escapeText(text?) static unescapeText(text?) static escapeAttr(attr?) static unescapeAttr(attr?) static strEval(str?) }
}
